### ISSUE TITLE
LCD read broken (at least on old version)

### ISSUE THREAD

**Issue by furrtek** [sharebrained/portapack-hackrf#114] opened 2017-08-11 18:18 UTC
It seems that the LCD read signal polarity change in 751ae92509027332ecd2a08e0b776d90cdcf0a51 causes data returned to be all bits stuck to 1. Screenshots are all white whatever is displayed.

**Comment by jboone** [comment] 2017-08-11 21:52
This appears to be due to gross negligence on my part. Fix forthcoming...

**Comment by jboone** [comment] 2017-08-11 22:00
Fix committed above. Please test and verify that it works for you. I was able to reproduce the issue and test the fix here, but apparently, I shouldn't trust myself...

**Comment by furrtek** [comment] 2017-08-11 23:00
Tested and verified, read_pixels() is now working. Thanks :)

**Comment by jboone** [comment] 2017-08-12 02:31
Excellent. Thanks for checking, and for finding this to begin with. I'm a bit surprised it worked at all. Apparently the CPLD tools picked the same LCD_WRX pin as I'd intended, by my dumb luck.

**Closed by jboone** 2017-08-12 02:31 UTC
